import csv
import io
from typing import Dict, Any, List

# IPS upload column order (matches V7 IPS upload tab)
IPS_COLUMNS = [
    "pricing_request_id", "Client", "Effective", "Expiration", "award_status",
    "incoterms", "shipping_terms", "client_target_rate", "target_terms", "loss_reason",
    "existing_client", "origin_country", "origin_address", "origin_city", "origin_state",
    "origin_postal_code", "Origin Airport", "origin_gateway",
    "destination_country", "destination_address", "destination_city", "destination_state",
    "destination_postal_code", "Destination Airport", "destination_gateway",
    "total_no_shipments", "total_actual_weight_kg", "total_volume_cbm",
    "volumetric_weight", "chargeable_weight", "density_profile", "avg_shipment",
    "requested_transit_time_min", "requested_transit_time_max",
    "packaging", "stackable", "dangerous_goods", "customer_notes",
    "tonnage_cap", "cap_frequency", "Service Tier",
    "origin_currency", "pickup_min", "pickup_kg_100", "pickup_kg_500",
    "pickup_kg_1000", "pickup_kg_2000", "pickup_kg_5000", "pickup_ftl", "pickup_ftl_capacity",
    "Origin Terminal Handling Charge", "Screening Charge", "Document", "Export Customs Clearance",
    "pickup_transit_time", "Currency", "buy_rate_basis", "assumed_fixed_percentage",
    "Minimum", "45kg", "100kg", "300kg", "500kg", "1000kg", "2000kg", "assumed_investment",
    "Fuel Surcharge", "Security Charge", "Automated Manifest System",
    "Entry Summary Declaration (ENS)", "Air Cargo Advanced Screening", "Peak Season Surcharge",
    "pss_effective", "pss_expiration", "airline_carrier", "flight_routing",
    "days_of_uplift", "no_flights_per_week", "main_transit_time_min", "main_transit_time_max",
    "destination_currency", "delivery_min", "delivery_kg_100", "delivery_kg_500",
    "delivery_kg_1000", "delivery_kg_2000", "delivery_kg_5000", "delivery_ftl", "delivery_ftl_capacity",
    "Destination Terminal Handling Charge", "Import Service Charge",
    "Import Customs Clearance", "Document Turnover Charge", "delivery_transit_time",
    "pickup_markup_kg", "pickup_markup_flat", "air_base_markup",
    "delivery_markup_kg", "delivery_markup_flat",
    "round", "origin_carrier", "origin_service_area", "destination_carrier", "destination_service_area",
]


def lane_to_ips_row(lane: Dict[str, Any], bid_data: Dict[str, Any]) -> Dict[str, Any]:
    """Map a lane dict to IPS upload column format."""
    return {
        "pricing_request_id": bid_data.get("pricing_request_id", ""),
        "Client": bid_data.get("client_name", ""),
        "Effective": lane.get("effective_date", ""),
        "Expiration": lane.get("expiration_date", ""),
        "award_status": lane.get("award_status", ""),
        "incoterms": lane.get("incoterms", ""),
        "shipping_terms": lane.get("shipping_terms", ""),
        "client_target_rate": lane.get("client_target_rate", ""),
        "target_terms": "",
        "loss_reason": "",
        "existing_client": "",
        "origin_country": lane.get("origin_country", ""),
        "origin_address": lane.get("origin_address", ""),
        "origin_city": lane.get("origin_city", ""),
        "origin_state": lane.get("origin_state", ""),
        "origin_postal_code": lane.get("origin_postal_code", ""),
        "Origin Airport": lane.get("origin_airport", ""),
        "origin_gateway": lane.get("origin_airport", ""),
        "destination_country": lane.get("destination_country", ""),
        "destination_address": lane.get("destination_address", ""),
        "destination_city": lane.get("destination_city", ""),
        "destination_state": lane.get("destination_state", ""),
        "destination_postal_code": lane.get("destination_postal_code", ""),
        "Destination Airport": lane.get("destination_airport", ""),
        "destination_gateway": lane.get("destination_airport", ""),
        "total_no_shipments": lane.get("total_shipments", ""),
        "total_actual_weight_kg": lane.get("total_actual_weight_kg", ""),
        "total_volume_cbm": lane.get("total_volume_cbm", ""),
        "volumetric_weight": lane.get("volumetric_weight_kg", ""),
        "chargeable_weight": lane.get("chargeable_weight_kg", ""),
        "density_profile": lane.get("density_profile", ""),
        "avg_shipment": lane.get("avg_shipment_kg", ""),
        "requested_transit_time_min": lane.get("transit_min", ""),
        "requested_transit_time_max": lane.get("transit_max", ""),
        "packaging": lane.get("packaging", ""),
        "stackable": lane.get("stackable", ""),
        "dangerous_goods": lane.get("dangerous_goods", ""),
        "customer_notes": lane.get("customer_notes", ""),
        "tonnage_cap": lane.get("tonnage_cap", ""),
        "cap_frequency": lane.get("cap_frequency", ""),
        "Service Tier": lane.get("service_tier", ""),
        "origin_currency": lane.get("origin_currency", "USD"),
        "pickup_min": lane.get("pickup_min", ""),
        "pickup_kg_100": lane.get("pickup_kg_100", ""),
        "pickup_kg_500": lane.get("pickup_kg_500", ""),
        "pickup_kg_1000": lane.get("pickup_kg_1000", ""),
        "pickup_kg_2000": lane.get("pickup_kg_2000", ""),
        "pickup_kg_5000": "",
        "pickup_ftl": "",
        "pickup_ftl_capacity": "",
        "Origin Terminal Handling Charge": lane.get("origin_thc", ""),
        "Screening Charge": lane.get("screening", ""),
        "Document": lane.get("doc_fee", ""),
        "Export Customs Clearance": lane.get("export_customs", ""),
        "pickup_transit_time": "",
        "Currency": lane.get("main_currency", "USD"),
        "buy_rate_basis": lane.get("buy_rate_basis", "per kg"),
        "assumed_fixed_percentage": "",
        "Minimum": lane.get("buy_rate_min", ""),
        "45kg": lane.get("buy_rate_45", ""),
        "100kg": lane.get("buy_rate_100", ""),
        "300kg": lane.get("buy_rate_300", ""),
        "500kg": lane.get("buy_rate_500", ""),
        "1000kg": lane.get("buy_rate_per_kg", ""),
        "2000kg": lane.get("buy_rate_2000", ""),
        "assumed_investment": "",
        "Fuel Surcharge": lane.get("fuel_surcharge", ""),
        "Security Charge": lane.get("security_charge", ""),
        "Automated Manifest System": lane.get("ams_ens", ""),
        "Entry Summary Declaration (ENS)": lane.get("ens", ""),
        "Air Cargo Advanced Screening": lane.get("acas", ""),
        "Peak Season Surcharge": lane.get("pss", ""),
        "pss_effective": lane.get("pss_effective", ""),
        "pss_expiration": lane.get("pss_expiration", ""),
        "airline_carrier": lane.get("airline", ""),
        "flight_routing": lane.get("routing", ""),
        "days_of_uplift": lane.get("days_of_uplift", ""),
        "no_flights_per_week": lane.get("flights_per_week", ""),
        "main_transit_time_min": lane.get("transit_min", ""),
        "main_transit_time_max": lane.get("transit_max", ""),
        "destination_currency": lane.get("dest_currency", "USD"),
        "delivery_min": lane.get("delivery_min", ""),
        "delivery_kg_100": lane.get("delivery_kg_100", ""),
        "delivery_kg_500": lane.get("delivery_kg_500", ""),
        "delivery_kg_1000": lane.get("delivery_kg_1000", ""),
        "delivery_kg_2000": lane.get("delivery_kg_2000", ""),
        "delivery_kg_5000": "",
        "delivery_ftl": "",
        "delivery_ftl_capacity": "",
        "Destination Terminal Handling Charge": lane.get("dest_thc", ""),
        "Import Service Charge": lane.get("import_service", ""),
        "Import Customs Clearance": lane.get("import_customs", ""),
        "Document Turnover Charge": lane.get("doc_turnover", ""),
        "delivery_transit_time": "",
        "pickup_markup_kg": lane.get("pickup_markup_kg", ""),
        "pickup_markup_flat": lane.get("pickup_markup_flat", ""),
        "air_base_markup": lane.get("air_base_markup", ""),
        "delivery_markup_kg": lane.get("delivery_markup_kg", ""),
        "delivery_markup_flat": lane.get("delivery_markup_flat", ""),
        "round": lane.get("round", "1"),
        "origin_carrier": "",
        "origin_service_area": "",
        "destination_carrier": "",
        "destination_service_area": "",
    }


def generate_ips_csv(bid_data: Dict[str, Any]) -> str:
    """Generate IPS upload CSV string from bid data."""
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=IPS_COLUMNS, extrasaction="ignore")
    writer.writeheader()
    for lane in bid_data.get("lanes", []):
        row = lane_to_ips_row(lane, bid_data)
        writer.writerow(row)
    return output.getvalue()
